---
image: python:3.6

stages:
  - setup
  - test

# -----------------------------------------------------------------------------
setup:py:
  stage: setup
  only:
    - master
  script:
    - python3 setup.py test
    - python3 setup.py install

setup:pip:
  stage: setup
  script:
    - pip3 install .

setup:venv:
  # NOTE This step is required for the next stages to have all dependencies:
  stage: setup
  script:
    # create a virtual env in the current directory
    - python3 -m venv env
    # enter virtual environment and install into it, including test deps
    - source ./env/bin/activate
    - pip3 install .[test_deps]
  artifacts:
    paths:
      - env/                        # to pass the environment to the next stage
    expire_in: 10min                # to not let them persist on the server
    # NOTE keep track of a feature to expire at end of pipeline
    # https://gitlab.com/gitlab-org/gitlab-ce/issues/19505


# -----------------------------------------------------------------------------
test:all:
  stage: test
  dependencies:
    - setup:venv
  script:
    # enter the virtual environment passed over from the last stage
    - source ./env/bin/activate
    - python3 -m pytest tests/ -v --cov=dantro --cov-report=term-missing
